"""add avatar nickname to user model

Revision ID: 07680eeac12f
Revises: d74aa789647f
Create Date: 2025-12-24 01:22:18.260950

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '07680eeac12f'
down_revision: Union[str, Sequence[str], None] = 'd74aa789647f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('auth_users', sa.Column('nickname', sa.String(length=255), nullable=True))
    op.add_column('auth_users', sa.Column('avatar', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('auth_users', 'avatar')
    op.drop_column('auth_users', 'nickname')
    # ### end Alembic commands ###
