"""add display name for role

Revision ID: 2ab844e04a4a
Revises: c7d609ab9a70
Create Date: 2026-01-02 17:27:27.054726

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ab844e04a4a'
down_revision: Union[str, Sequence[str], None] = 'c7d609ab9a70'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('auth_roles', sa.Column('display_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('auth_roles', 'display_name')
    # ### end Alembic commands ###
