"""update user/invitecode/ragflow tables

Revision ID: 7fa4513384c9
Revises: 07680eeac12f
Create Date: 2025-12-30 16:58:09.610753

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7fa4513384c9'
down_revision: Union[str, Sequence[str], None] = '07680eeac12f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth_invite_codes',
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=True),
    sa.Column('used_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['used_by'], ['auth_users.id'], ),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_index(op.f('ix_auth_invite_codes_code'), 'auth_invite_codes', ['code'], unique=False)
    op.create_index(op.f('ix_auth_invite_codes_used_by'), 'auth_invite_codes', ['used_by'], unique=False)
    op.add_column('auth_permissions', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('auth_permissions', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('auth_roles', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('auth_roles', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('auth_users', sa.Column('is_superuser', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('auth_users', 'is_superuser')
    op.drop_column('auth_roles', 'updated_at')
    op.drop_column('auth_roles', 'created_at')
    op.drop_column('auth_permissions', 'updated_at')
    op.drop_column('auth_permissions', 'created_at')
    op.drop_index(op.f('ix_auth_invite_codes_used_by'), table_name='auth_invite_codes')
    op.drop_index(op.f('ix_auth_invite_codes_code'), table_name='auth_invite_codes')
    op.drop_table('auth_invite_codes')
    # ### end Alembic commands ###
