"""rename hashed_password field

Revision ID: aaa87b44ddad
Revises: 2ab844e04a4a
Create Date: 2026-01-02 23:41:00.155368

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aaa87b44ddad'
down_revision: Union[str, Sequence[str], None] = '2ab844e04a4a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'auth_users',
        'hashed_password',
        new_column_name='password',
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'auth_users',
        'password',
        new_column_name='hashed_password',
    )
    # ### end Alembic commands ###
