"""add fields for user

Revision ID: cfac8e7fdbe4
Revises: aaa87b44ddad
Create Date: 2026-01-03 01:09:42.433766

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cfac8e7fdbe4'
down_revision: Union[str, Sequence[str], None] = 'aaa87b44ddad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('auth_users', sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('auth_users', sa.Column('email', sa.String(length=64), nullable=True))
    op.add_column('auth_users', sa.Column('mobile', sa.String(length=32), nullable=True))
    op.alter_column('auth_users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('auth_users', 'is_superuser',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.create_index(op.f('ix_auth_users_email'), 'auth_users', ['email'], unique=True)
    op.create_index(op.f('ix_auth_users_mobile'), 'auth_users', ['mobile'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_auth_users_mobile'), table_name='auth_users')
    op.drop_index(op.f('ix_auth_users_email'), table_name='auth_users')
    op.alter_column('auth_users', 'is_superuser',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('auth_users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_column('auth_users', 'mobile')
    op.drop_column('auth_users', 'email')
    op.drop_column('auth_users', 'last_login_at')
    # ### end Alembic commands ###
